[project]
name = "lambdas"
version = "0.1.0"
description = "aws lambda function code"
authors = [{name = "Second Brain Team"}]
license = {text = "MIT"}
requires-python = ">=3.9"
dependencies = [
    "boto3==1.42.30",
    "botocore==1.42.30",
    "requests==2.28.0",
    "anthropic==0.76.0",
    "openai==1.109.1",
    "pydantic==2.12.5",
    "common",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint.flake8-tidy-imports]
banned-module-level-imports = [
    "cdk",
]