[project]
name = "common"
version = "0.1.0"
description = "utilities for local scripts, cdk, lambdas"
authors = [{name = "Second Brain Team"}]
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "dotenv==0.9.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"